name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container & Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        env:
          VUE_APP_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          VUE_APP_API_URL:  ${{ secrets.API_URL }}
        with:
          name: polarizedions/disquotes-ui
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
          registry: ghcr.io
          tags: "latest,${{ github.run_number }}"
          buildargs: VUE_APP_CLIENT_ID,VUE_APP_API_URL
